const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const ts = require('../coffee_app/node_modules/typescript')
const source = fs.readFileSync(path.join(__dirname, '..', 'coffee_app/src/main.tsx'), 'utf8')
const styles = fs.readFileSync(path.join(__dirname, '..', 'coffee_app/src/style.css'), 'utf8')
const maps = source.split('\n').filter(line => /^const bean(Processes|RoastLevels)=/.test(line.trim())).join('\n')
const summaryFunction = source.split('\n').find(line => line.trim().startsWith('function beanSummary('))
const summary = new Function(ts.transpile(`${maps}\n${summaryFunction}\nreturn beanSummary`))()

assert.equal(
  summary({origin:'Ethiopia, Yirgacheffe',variety:'Heirloom',process:'washed',roast_level:'light',single_origin:'single_origin',decaf:true}),
  'Ethiopia, Yirgacheffe · Heirloom · Washed · Light roast · Single origin · Decaf'
)
assert.equal(summary({process:'natural',roast_level:'medium_dark'}),'Natural · Medium-dark roast')
assert.equal(summary({single_origin:'blend',decaf:false}),'Blend')
assert.equal(summary({}),'')
assert.match(source, /beanSelectField\('process','Process'/)
assert.match(source, /\['wet_hulled','Wet hulled'\]/)
assert.match(source, /beanSelectField\('roast_level','Roast level'/)
assert.match(source, /\['medium_dark','Medium-dark'\]/)
assert.match(source, /beanChoiceField\('single_origin','Single origin or blend'/)
assert.match(source, /function decafField\(\)/)
assert.match(source, /function beanOriginField\(\)/)
assert.match(source, /list="common-origins"/)
const originsLine = source.split('\n').find(line => line.trim().startsWith('const commonOrigins='))
const origins = new Function(ts.transpile(`${originsLine}\nreturn commonOrigins`))()
assert.ok(origins.length >= 20)
for (const origin of ['Ethiopia','Colombia','Brazil','Kenya','Panama']) assert.ok(origins.includes(origin))
assert.match(source, /\['','Not set'\]/)
assert.match(styles, /input::placeholder, textarea::placeholder \{ color: #a9a9a9; opacity: 1; \}/)
assert.match(styles, /select:has\(option\[value=""\]:checked\) \{ color: #a9a9a9; \}/)
assert.match(styles, /select option \{ color: var\(--ink\); \}/)
console.log('Bean details: structured selections summarize into the coffee meta line; origin suggests common origins but stays free text; suggested text is muted until set.')
