const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const ts = require('../coffee_app/node_modules/typescript')
const source = fs.readFileSync(path.join(__dirname, '..', 'coffee_app/src/main.tsx'), 'utf8')
const functions = ['dateInput', 'roastWindow'].map(name => source.split('\n').find(line => line.trim().startsWith(`function ${name}(`))).join('\n')
const windowFor = new Function('today', ts.transpile(`${functions}\nreturn roastWindow`))(() => '2026-09-15')

assert.equal(windowFor('2026-09-09').state, 'resting')
assert.equal(windowFor('2026-09-08').state, 'optimal')
assert.equal(windowFor('2026-08-18').state, 'optimal')
assert.equal(windowFor('2026-08-17').state, 'past')
assert.equal(windowFor('').state, 'unknown')
console.log('Roast window: resting through day 6, optimal days 7–28, then past peak.')
