const assert = require('node:assert/strict')
const fs = require('node:fs')
const ts = require('../coffee_app/node_modules/typescript')
const path = require('node:path')
const root = path.resolve(__dirname, '..')
const source = fs.readFileSync(path.join(root, 'coffee_app/src/main.tsx'), 'utf8')
const api = fs.readFileSync(path.join(root, 'coffee_app/src/api.ts'), 'utf8')
const names = ['shotTime', 'originalOrder', 'newestFirst', 'repeat', 'newShot', 'shotForEdit', 'changeSetting']
const functions = names.map(name => source.split('\n').find(line => line.trim().startsWith(`function ${name}(`))).join('\n')
const defaults = api.split('\n').filter(line => /^export const (today|blankShot)=/.test(line)).map(line => line.replace('export ', '')).join('\n')
const code = ts.transpile(`${defaults}\n${functions}\nnewShot();return draft;`)
const create = new Function('shots', 'selected', 'profile', `let draft;const grindEdited={current:false};const setDraft=value=>{draft=value};${code}`)
const change = new Function('shots','d','value','edited',ts.transpile(`const grindEdited={current:edited};${functions}\nreturn changeSetting(d,'paper',value);`))
const forEdit = new Function('s','profile',ts.transpile(`${defaults}\n${functions}\nreturn shotForEdit(s);`))
const profile={defaults:{dose:14,grind:'8',paper:'yes',temp:'I',basket:'test basket',puckScreen:'yes'}}
const old = {coffee_id:'a',status:'logged',date:'2026-09-09',recorded_at:'2026-09-09T01:00:00Z',dose:14,grind:'5',paper:'yes',temp:'I'}
const latest = {...old,recorded_at:'2026-09-09T02:00:00Z',dose:15,grind:'6',paper:'no',temp:'0',basket:'test basket',puck_screen:'no',target_yield_g:30,stop_yield_g:30.5,yield_g:31,seconds:27,taste:'nice',rating:5,choked:true,id:'old',revision:3}
const draft = create([old,latest,{...latest,coffee_id:'b',date:'2026-09-10'},{...latest,status:'planned',date:'2026-09-11'}],'a',profile)
const planned = {...latest,status:'planned',date:'2026-09-11',recorded_at:undefined}
const recorded = forEdit(planned,profile)
assert.equal(recorded.status,'logged')
assert.match(recorded.date,/^\d{4}-\d{2}-\d{2}$/)
assert.equal(recorded.recorded_at,undefined)
assert.deepEqual(forEdit(latest,profile),latest)
for(const key of ['dose','grind','paper','temp','basket','puck_screen','target_yield_g']) assert.equal(draft[key],latest[key])
assert.equal(draft.yield_g,null)
assert.equal(draft.stop_yield_g,null)
assert.equal(draft.seconds,null)
assert.equal(draft.taste,'')
assert.equal(draft.rating,undefined)
assert.equal(draft.choked,undefined)
assert.equal(draft.id,undefined)
assert.equal(draft.recorded_at,undefined)
assert.equal(draft.revision,0)
draft.paper='yes'
assert.equal(draft.paper,'yes')
assert.equal(change([old,latest],draft,'yes',false).grind,'5')
assert.equal(change([old,latest],draft,'no',false).grind,'6')
assert.equal(change([old,latest],{...draft,grind:'7'},'no',true).grind,'7')
assert.equal(change([old,latest],{...draft,id:'existing',grind:'7'},'no',false).grind,'7')
assert.equal(change([latest],draft,'yes',false).grind,'')
const fresh=create([],'new-coffee',profile)
assert.equal(fresh.coffee_id,'new-coffee')
assert.equal(fresh.dose,14)
assert.equal(fresh.grind,'8')
console.log('New shot defaults and planned-shot editing: settings copied; results cleared; recorded plans become logged.')
