const assert = require('node:assert/strict')
const fs = require('node:fs')
const ts = require('../coffee_app/node_modules/typescript')
const source = fs.readFileSync(require('node:path').join(__dirname,'../coffee_app/src/shotEditing.ts'),'utf8')
const moduleRef = {exports:{}}
new Function('module','exports',ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(moduleRef,moduleRef.exports)
const {inlineShotPatch,plannedEditorFields,loggedEditorFields,plannedStopAt} = moduleRef.exports
const shot={id:'plan',coffee_id:'bag',revision:4,status:'planned',dose:18,grind:'5.0',target_yield_g:36,target_yield_max_g:40,yield_g:null,rating:null}
const edit=(field,value)=>({shot,field,value})
assert.deepEqual(inlineShotPatch(edit('grind','4.9')),{coffee_id:'bag',revision:4,grind:'4.9'})
assert.deepEqual(inlineShotPatch(edit('dose','18.5')),{coffee_id:'bag',revision:4,dose:18.5})
assert.deepEqual(inlineShotPatch(edit('target_yield_g','38')),{coffee_id:'bag',revision:4,target_yield_g:38,target_yield_max_g:null,stop_yield_g:null})
assert.deepEqual(inlineShotPatch(edit('target_yield_g','')),{coffee_id:'bag',revision:4,target_yield_g:null,target_yield_max_g:null,stop_yield_g:null})
assert.equal(plannedStopAt({...shot,stop_yield_g:30}),30)
assert.equal(plannedStopAt(shot),36)
assert.deepEqual(loggedEditorFields(['dose','target_yield_g','yield_g','stop_yield_g','seconds']),['dose','stop_yield_g','yield_g','seconds'])
assert.deepEqual(inlineShotPatch({...edit('target_yield_g','32'),shot:{...shot,stop_yield_g:30}}),{coffee_id:'bag',revision:4,target_yield_g:32,target_yield_max_g:null,stop_yield_g:null})
assert.throws(()=>inlineShotPatch(edit('dose','0')),/more than 0/)
assert.throws(()=>inlineShotPatch(edit('dose','nope')),/Enter/)
assert.throws(()=>inlineShotPatch(edit('water_temp_c','101')),/Enter/)
assert.throws(()=>inlineShotPatch(edit('yield_g','40')),/after brewing/)
assert.throws(()=>inlineShotPatch(edit('seconds','30')),/after brewing/)
assert.deepEqual(inlineShotPatch({...edit('yield_g','40'),shot:{...shot,status:'logged'}}),{coffee_id:'bag',revision:4,yield_g:40})
assert.deepEqual(plannedEditorFields(['dose','grind','yield_g','target_yield_g','stop_yield_g','seconds','rating','temp','water_g','first_drip']),['dose','grind','target_yield_g','temp','water_g'])
const ratedEdit=value=>({...edit('rating',value),shot:{...shot,status:'logged'}})
assert.deepEqual(inlineShotPatch(ratedEdit('5')),{coffee_id:'bag',revision:4,rating:5})
assert.deepEqual(inlineShotPatch(ratedEdit('')),{coffee_id:'bag',revision:4,rating:null})
for(const value of ['0','6','3.5'])assert.throws(()=>inlineShotPatch(ratedEdit(value)))
assert.throws(()=>inlineShotPatch(edit('rating','4')),/after brewing/)
assert.equal(shot.status,'planned')
assert.equal(shot.yield_g,null)
assert.equal(shot.rating,null)
console.log('Inline edits: partial revisioned saves, single stop target, validation, and planned recipe boundaries passed.')
