import {useEffect,useRef,useState} from 'react'
import {api,blankShot,today} from './api'
import type {Coffee,Shot,Message} from './api'
import ChatComposer from './components/chat/ChatComposer'
import ThinkingCounter from './components/chat/ThinkingCounter'
import {marked} from 'marked'
import DOMPurify from 'dompurify'
import Icon from './components/ui/Icon'
import './style.css'
import LoadingLogbook from './components/LoadingLogbook'
import {profile} from './profile'
const balances={sour:'Sour',slightly_sour:'Slightly sour',balanced:'Balanced',slightly_bitter:'Slightly bitter',bitter:'Bitter / burnt'} as const
declare const process:{env:{BUILD_TIME?:string;APP_VERSION?:string}}
const buildTime=process.env.BUILD_TIME||''
function lastCoffee(){try{return localStorage.getItem('coffee.selected')||''}catch{return ''}}

const outcomes={unrated:'Unrated',good:'Well brewed',adjust:'Needs adjustment',bad:'Failed',choked:'Choked'} as const
const markerColors=['black','red','orange','green','blue','purple'] as const
function dateInput(value:string){if(/^\d{4}-\d{2}-\d{2}$/.test(value))return value;const match=value.match(/^(\d{1,2}) (January|February|March|April|May|June|July|August|September|October|November|December) (\d{4})$/i);if(!match)return '';const month=['january','february','march','april','may','june','july','august','september','october','november','december'].indexOf(match[2].toLowerCase())+1;return match[3]+'-'+String(month).padStart(2,'0')+'-'+match[1].padStart(2,'0')}
function roastWindow(roastDate:string){const iso=dateInput(roastDate);if(!iso)return {state:'unknown',label:'Roast date unknown'};const age=Math.floor((new Date(today()+'T12:00:00').valueOf()-new Date(iso+'T12:00:00').valueOf())/86400000);if(age<0)return {state:'unknown',label:'Roast date ahead'};if(age<7)return {state:'resting',label:`Resting · ${7-age}d to go`};if(age<=28)return {state:'optimal',label:`Optimal · ${29-age}d left`};return {state:'past',label:`Past peak · day ${age}`}}
function RoastWindow({roastDate,compact=false}:{roastDate:string;compact?:boolean}){const window=roastWindow(roastDate);return <span className={'roast-window '+window.state+(compact?' compact':'')} title={window.label}><span className="roast-track" aria-hidden="true"><i className={window.state==='resting'?'active':''}/><i className={window.state==='optimal'?'active':''}/><i className={window.state==='past'?'active':''}/></span><span>{window.label}</span></span>}
function targetYield(s:Shot){return s.target_yield_g==null?null:s.target_yield_max_g!=null&&s.target_yield_max_g!==s.target_yield_g?`${s.target_yield_g}–${s.target_yield_max_g}`:String(s.target_yield_g)}
function dripThrough(s:Shot){return s.stop_yield_g!=null&&s.yield_g!=null&&s.yield_g>s.stop_yield_g?(s.yield_g-s.stop_yield_g).toFixed(1):null}
function shotTime(s:Shot){const value=s.date&&new Date(s.date.length===10?s.date+'T12:00:00':s.date).valueOf();return typeof value==='number'&&!Number.isNaN(value)?value:null}
function formatShotDate(s:Shot){const value=shotTime(s);return value==null?'Date not recorded':new Date(value).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})+(s.recorded_at?' · '+new Date(s.recorded_at).toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'}):'')}
function originalOrder(s:Shot){const match=s.id?.match(/^import-(\d+)$/);return match?Number(match[1]):null}
function newestFirst(rows:Shot[]){return [...rows].sort((a,b)=>{const aTime=shotTime(a),bTime=shotTime(b);if(aTime!=null&&bTime!=null)return bTime-aTime||(Date.parse(b.recorded_at||'')||0)-(Date.parse(a.recorded_at||'')||0);if(aTime!=null)return -1;if(bTime!=null)return 1;const aOrder=originalOrder(a),bOrder=originalOrder(b);if(aOrder!=null&&bOrder!=null)return aOrder-bOrder;if(aOrder!=null)return -1;if(bOrder!=null)return 1;return 0})}

export default function App({onLogout}:{onLogout?:()=>void}){
 const grindEdited=useRef(false)
 const [paperFilter,setPaperFilter]=useState('all')
 const [coffees,setCoffees]=useState<Coffee[]>([]),[shots,setShots]=useState<Shot[]>([]),[messages,setMessages]=useState<Message[]>([])
 const [selected,setSelected]=useState(lastCoffee),[tab,setTab]=useState('shots'),[filter,setFilter]=useState('logged'),[draft,setDraft]=useState<Shot|null>(null)
 const [coffeeDraft,setCoffeeDraft]=useState<Partial<Coffee>|null>(null),[input,setInput]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false)
 const [job,setJob]=useState<string|null>(null),[sending,setSending]=useState(false)
 const [locking,setLocking]=useState<Set<string>>(()=>new Set())
 const messagesView=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null),coffeePicker=useRef<HTMLDetailsElement>(null)
 async function refresh(){const state=await api('/state');const active=state.coffees.filter((c:Coffee)=>!c.archived);setCoffees(state.coffees);setShots(state.shots);setMessages(state.messages);setSelected(prev=>active.some((c:Coffee)=>c.id===prev)?prev:active.at(-1)?.id||'');if(state.active_job)setJob(state.active_job.id);setLoading(false)}
 useEffect(()=>{if(!loading)try{localStorage.setItem('coffee.selected',selected)}catch{}},[selected,loading])
 async function removeRecord(){const row=draft||coffeeDraft;if(!row?.id)return;const kind=draft?'shot':'coffee';if(!window.confirm(kind==='coffee'?`Delete ${coffeeDraft?.name} and remove all its shots from your logbook?`:'Delete this shot?'))return;setSaving(true);setError('');try{await api(`/${kind==='coffee'?'coffees':'shots'}/${row.id}?revision=${row.revision}`,'DELETE');setDraft(null);setCoffeeDraft(null);await refresh()}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 useEffect(()=>{refresh().catch(e=>{setError(e.message);setLoading(false)})},[])
 useEffect(()=>{if(draft||coffeeDraft)dialog.current?.showModal();else dialog.current?.close()},[!!draft,!!coffeeDraft])
 useEffect(()=>{const list=messagesView.current;list?.scrollTo({top:list.scrollHeight,behavior:'smooth'})},[messages,job,tab])
 useEffect(()=>{
  const viewport=window.visualViewport,root=document.documentElement
  let frame=0,baseline=Math.max(window.innerHeight,root.clientHeight)
  const timers=new Set<number>()
  const update=()=>{
   frame=0
   const focused=document.activeElement?.matches('input,textarea,[contenteditable="true"]')
   const inset=viewport?Math.max(0,baseline-viewport.height-viewport.offsetTop):0
   // AIFit: retain keyboard geometry through transient iOS focus loss.
   const keyboard=!!viewport&&(!!focused||inset>120)
   if(!keyboard)baseline=Math.max(window.innerHeight,root.clientHeight)
   root.style.setProperty('--app-height',`${viewport?.height||window.innerHeight}px`)
   root.style.setProperty('--app-offset-top',`${viewport?.offsetTop||0}px`)
   root.toggleAttribute('data-keyboard-open',!!viewport&&inset>120)
   // Do not fight Safari while it is aligning a focused field.
   if(!keyboard&&(window.scrollY||window.scrollX))window.scrollTo(0,0)
  }
  const soon=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(update)}
  const settled=()=>{soon();for(const delay of [80,260]){const id=window.setTimeout(()=>{timers.delete(id);soon()},delay);timers.add(id)}}
  const orient=()=>{baseline=Math.max(window.innerHeight,root.clientHeight);settled()}
  update()
  viewport?.addEventListener('resize',soon);viewport?.addEventListener('scroll',soon)
  window.addEventListener('pageshow',settled);window.addEventListener('resize',soon);window.addEventListener('focusin',settled);window.addEventListener('focusout',settled);window.addEventListener('orientationchange',orient)
  return()=>{
   cancelAnimationFrame(frame);timers.forEach(clearTimeout)
   viewport?.removeEventListener('resize',soon);viewport?.removeEventListener('scroll',soon)
   window.removeEventListener('pageshow',settled);window.removeEventListener('resize',soon);window.removeEventListener('focusin',settled);window.removeEventListener('focusout',settled);window.removeEventListener('orientationchange',orient)
  }
 },[])
 useEffect(()=>{if(!job)return;let stopped=false;const poll=async()=>{try{const result=await api('/chat/'+encodeURIComponent(job));if(stopped)return;if(['complete','failed'].includes(result.status)){setJob(null);await refresh();if(result.status==='failed')setError(result.error||'Chat failed');}}catch(e){if(!stopped)setError((e as Error).message)}};poll();const timer=setInterval(poll,1500);return()=>{stopped=true;clearInterval(timer)}},[job])
 const activeCoffees=coffees.filter(c=>!c.archived), archivedCoffees=coffees.filter(c=>c.archived), coffee=coffees.find(c=>c.id===selected), visible=newestFirst(shots.filter(s=>s.coffee_id===selected&&s.status===filter&&(paperFilter==='all'||(paperFilter==='locked'?s.locked:s.paper===paperFilter))))
 const rated=shots.filter(s=>s.coffee_id===selected&&s.status==='logged'&&s.outcome==='good'&&!s.choked&&s.rating!=null)
 const average=rated.length?(rated.reduce((total,s)=>total+s.rating!,0)/rated.length).toFixed(1):null
 async function saveShot(){if(!draft)return;const recordingPlanned=!!draft.id&&draft.status==='logged'&&shots.some(s=>s.id===draft.id&&s.status==='planned');setSaving(true);setError('');try{await api(draft.id?'/shots/'+draft.id:'/shots',draft.id?'PUT':'POST',draft);if(recordingPlanned)setFilter('logged');setDraft(null);await refresh()}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function saveCoffee(){if(!coffeeDraft)return;setSaving(true);setError('');try{const saved=await api(coffeeDraft.id?'/coffees/'+coffeeDraft.id:'/coffees',coffeeDraft.id?'PUT':'POST',coffeeDraft);setCoffeeDraft(null);await refresh();setSelected(saved.id)}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function setCoffeeArchived(row:Coffee,archived:boolean){setSaving(true);setError('');try{const saved=await api('/coffees/'+row.id,'PUT',{...row,archived});setCoffeeDraft(null);await refresh();if(!archived)setSelected(saved.id)}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function toggleLocked(shot:Shot){if(!shot.id||locking.has(shot.id))return;setLocking(current=>new Set(current).add(shot.id!));setError('');try{const saved=await api('/shots/'+shot.id,'PUT',{coffee_id:shot.coffee_id,revision:shot.revision,locked:!shot.locked});setShots(rows=>rows.map(row=>row.id===saved.id?saved:row))}catch(e){setError((e as Error).message)}finally{setLocking(current=>{const next=new Set(current);next.delete(shot.id!);return next})}}
 async function send(){if(!input.trim()||job||sending)return;setSending(true);setError('');try{const result=await api('/chat','POST',{id:crypto.randomUUID(),message:input,coffee_id:selected||null,shot_date:today()});setInput('');setJob(result.id);await refresh()}catch(e){setError((e as Error).message)}finally{setSending(false)}}
 function repeat(s:Shot){grindEdited.current=false;setDraft({...blankShot(s.coffee_id),dose:s.dose,grind:s.grind,paper:s.paper,temp:s.temp,basket:s.basket,puck_screen:s.puck_screen,target_yield_g:s.target_yield_g??null,target_yield_max_g:s.target_yield_max_g??null,date:today()})}
 function newShot(){grindEdited.current=false;const last=newestFirst(shots.filter(s=>s.coffee_id===selected&&s.status==='logged'))[0];if(last)repeat(last);else setDraft(blankShot(selected))}
 function shotForEdit(s:Shot){return s.status==='planned'?{...s,status:'logged',date:today()}:s}
 function openShot(s:Shot){grindEdited.current=false;setDraft(shotForEdit(s))}
 function changeSetting(d:Shot,key:'paper'|'temp',value:string){const next={...d,[key]:value};if(key==='paper'&&!d.id&&!grindEdited.current){const match=newestFirst(shots.filter(s=>s.coffee_id===d.coffee_id&&s.status==='logged'&&s.paper===value&&value!=='unknown'&&s.grind.trim()!==''))[0];next.grind=match?.grind??''}return next}
 function field(key:keyof Shot,label:string,type='text'){return <label key={key}>{label}<input type={type} step={type==='number'?'any':undefined} min={type==='number'?0:undefined} value={String(draft?.[key]??'')} onChange={e=>{if(key==='grind')grindEdited.current=true;setDraft(d=>d?{...d,[key]:type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value}:d)}}/></label>}
 function selectField(key:keyof Shot,label:string,options:string[]){return <label key={key}>{label}<select value={String(draft?.[key]??'')} onChange={e=>setDraft(d=>d?{...d,[key]:e.target.value}:d)}>{options.map(v=><option key={v} value={v}>{v||'Unknown'}</option>)}</select></label>}
 function tapField(key:'paper'|'temp',label:string,options:string[][]){return <fieldset className="tap-picker"><legend>{label}</legend>{options.map(([value,text])=><button type="button" key={value} aria-pressed={draft?.[key]===value} onClick={()=>setDraft(d=>d?changeSetting(d,key,d[key]===value?(key==='paper'?'unknown':''):value):d)}>{text}</button>)}</fieldset>}
 return <div className="app-shell">
  <header className="app-top-bar">
   <a className="brand" href="#" onClick={e=>{e.preventDefault();setTab('shots')}}><span className="brand-icon"><Icon name="cup"/></span><span>coffee<span className="brand-sub">LOGBOOK</span></span></a>
   <nav aria-label="Primary">{['shots',...(profile.chatEnabled?['chat']:[])].map(t=><button key={t} aria-pressed={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}><Icon name={t==='chat'?'chat':'cup'}/>{t==='chat'?'Chat':'Shots'}</button>)}</nav>
   <div className="header-actions">{profile.setupLabel&&<span className="setup-label"><span className="status-dot"/>{profile.setupLabel}</span>}{onLogout&&<button className="sign-out-header" onClick={onLogout} aria-label="Sign out" title="Sign out"><Icon name="logout"/></button>}</div>
  </header>
  {error&&<div role="alert" className="error">{error}<button onClick={()=>setError('')} aria-label="Dismiss error">×</button></div>}
  {loading?<main className="loading-view"><LoadingLogbook/></main>:tab==='shots'?<main className="shots-view">
   <div className="heading">
    <div><div className="eyebrow">ESPRESSO LOGBOOK</div><h1>Shots</h1></div>
    <div className="shot-heading-actions"><div className="paper-filter" role="group" aria-label="Filter shots">{[['all','All'],['yes','Paper'],['no','No paper'],['locked','Locked']].map(([value,label])=><button key={value} type="button" aria-pressed={paperFilter===value} onClick={()=>{setPaperFilter(value);if(value==='locked')setFilter('logged')}}>{label}</button>)}</div><button className="primary" disabled={!coffee||coffee.archived} onClick={newShot}><Icon name="plus"/>Log shot</button></div>
   </div>
   <section className="coffee-panel" aria-label="Selected coffee">
    <div className="coffee-selection"><label>ON THE BAR</label><details className="coffee-picker" ref={coffeePicker}><summary aria-label="Choose coffee"><span>{coffee?.name||'Choose coffee'}</span>{coffee?.tag_color&&<span className={'coffee-marker '+coffee.tag_color} aria-hidden="true"/>}<span className="picker-chevron" aria-hidden="true">⌄</span></summary><div className="coffee-options">{activeCoffees.map(c=><button key={c.id} type="button" aria-pressed={selected===c.id} onClick={()=>{setSelected(c.id);coffeePicker.current?.removeAttribute('open')}}><span className="coffee-option-name">{c.name}</span>{c.tag_color&&<span className={'coffee-marker '+c.tag_color} aria-hidden="true"/>}<RoastWindow roastDate={c.roast_date} compact/></button>)}{!!archivedCoffees.length&&<details className="archived-coffees"><summary>Archived coffees ({archivedCoffees.length})</summary>{archivedCoffees.map(c=><div key={c.id}><button type="button" onClick={()=>{setSelected(c.id);coffeePicker.current?.removeAttribute('open')}}><span className="coffee-option-name">{c.name}</span>{c.tag_color&&<span className={'coffee-marker '+c.tag_color} aria-hidden="true"/>}<RoastWindow roastDate={c.roast_date} compact/></button><button type="button" className="restore-coffee" onClick={()=>setCoffeeArchived(c,false)}>Restore</button></div>)}</details>}</div></details>
    {coffee&&<div className="coffee-meta">{coffee.archived&&<span className="archived-badge">Archived</span>}<span>Roasted {coffee.roast_date||'date unknown'}</span><RoastWindow roastDate={coffee.roast_date}/><span className="meta-divider">·</span><span>{shots.filter(s=>s.coffee_id===selected&&s.status==='logged').length} shots logged</span>{average&&<span>★ {average}/5 · {rated.length} well-brewed shots</span>}<button className="text-button" onClick={()=>setCoffeeDraft(coffee)}>Bean details <Icon name="arrow"/></button>{!average&&<span>No rated well-brewed shots yet</span>}</div>}</div>
    <button className="add-coffee" aria-label="Add coffee" title="Add coffee" onClick={()=>setCoffeeDraft({name:'',roast_date:'',notes:'',revision:0})}><Icon name="plus"/><span>Add coffee</span></button>
   </section>
   <div className="list-heading"><div className="segmented">{['logged','planned'].map(f=><button key={f} aria-pressed={filter===f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f==='logged'?'Shot history':'Next tests'}<span>{shots.filter(s=>s.coffee_id===selected&&s.status===f).length}</span></button>)}</div>{profile.chatEnabled&&<button className="text-button ask-coffee" onClick={()=>{setInput('What should I try next with this coffee?');setTab('chat')}}><Icon name="chat"/>Dial it in <Icon name="arrow"/></button>}</div>
   {paperFilter!=='all'&&!visible.length&&<p className="list-order">No matching shots. <button className="text-button" onClick={()=>setPaperFilter('all')}>Show all</button></p>}
   {filter==='logged'&&<p className="list-order">Dated shots: newest first. Original records: oldest first, as recorded.</p>}
   <div className="shot-list">{visible.map((s,index)=><article className={'shot-card'+(s.locked?' locked':'')} key={s.id}>
    <div className="shot-top"><span className="shot-index">{String(visible.length-index).padStart(2,'0')}</span>{s.status==='logged'&&s.outcome&&s.outcome!=='unrated'&&<span className={'shot-outcome '+s.outcome}><span/>{s.choked?'Choked':outcomes[s.outcome]}</span>}{s.taste_balance&&<span className="shot-outcome">{balances[s.taste_balance]}</span>}{s.choked&&s.outcome!=='choked'&&<span className="shot-outcome">Choked</span>}{s.rating!=null&&<span className="shot-outcome">★ {s.rating}/5</span>}<span className="shot-date">{formatShotDate(s)}</span>{(s.source||s.status==='planned')&&<span className="record-badge">{s.source?'Original record':'Next test'}</span>}{s.status==='logged'&&<button type="button" className="lock-shot" aria-pressed={!!s.locked} aria-label={s.locked?'Unlock this dialed-in shot':'Lock this dialed-in shot'} title={s.locked?'Unlock this shot':'Mark as dialed in'} disabled={locking.has(s.id||'')} onClick={()=>toggleLocked(s)}><Icon name="lock"/>{s.locked?'Locked':'Lock'}</button>}<button className="text-button recipe-button" disabled={coffee?.archived} onClick={()=>repeat(s)}>Use recipe <Icon name="arrow"/></button></div>
    <button className="shot-body" onClick={()=>openShot(s)} aria-label={`Edit shot ${s.id}`}>
     <div className="shot-measurements"><div className="metrics">{[[s.dose,'g','DOSE'],[s.status==='planned'?targetYield(s):s.yield_g,'g',s.status==='planned'?'TARGET OUT':'OUT'],[s.seconds,'s','TIME'],[s.grind||null,'','GRIND']].map(([v,unit,label])=><div key={String(label)}><span className="metric-label">{label}</span><div><strong>{v??'—'}</strong><span className="metric-unit">{unit}</span></div>{label==='OUT'&&s.stop_yield_g!=null&&<small className="stop-yield">stop {s.stop_yield_g} g</small>}</div>)}</div>
     <div className="shot-settings"><span className="ratio">{s.status==='planned'?'Target output':s.dose&&s.yield_g?'1 : '+(s.yield_g/s.dose).toFixed(2):'Ratio —'}</span><span className="shot-setting-badges"><span className={'setting-badge paper-'+(s.paper==='yes'?'yes':s.paper==='no'?'no':'unknown')}>{s.paper==='yes'?'Paper':s.paper==='no'?'No paper':'Paper ?'}</span><span className="setting-badge temp-badge" data-temp={s.temp||'unknown'}>Temp <strong>{s.temp||'—'}</strong></span></span>{dripThrough(s)&&<span className="drip-through">+{dripThrough(s)} g drip</span>}{s.pressure&&<span>{s.pressure}</span>}</div><span className="edit-indicator"><Icon name="edit"/></span></div>
     <p className="taste"><span>{s.source?'ORIGINAL NOTE':'NOTE'}</span>{s.taste||'Add a tasting note…'}</p>
    </button>
    {s.source&&<details className="original-record"><summary>View original logbook row</summary><p>{s.source}</p></details>}
   </article>)}{!visible.length&&paperFilter==='all'&&<div className="empty"><Icon name="cup"/><h2>{filter==='logged'?'A fresh page.':'Room to experiment.'}</h2><p>{coffee?(profile.chatEnabled?'Log a shot or ask chat to plan your next brew.':'Log a shot to start dialing in this coffee.'):'Add your first coffee to start your journal.'}</p><button className="text-button" onClick={()=>coffee?newShot():setCoffeeDraft({name:'',revision:0})}>{coffee?'Log your first shot':'Add coffee'} <Icon name="arrow"/></button></div>}</div>
   <footer className="journal-footer"><span>Coffee logbook</span>{profile.setupLabel&&<span>{profile.setupLabel}</span>}</footer>
  </main>:<main className="chat-view"><div className="chat-heading"><div><div className="eyebrow">COFFEE ASSISTANT</div><h1>Chat</h1></div></div><div className="messages" ref={messagesView}>{!messages.length&&<div className="chat-welcome"><span className="welcome-icon"><Icon name="cup"/></span><h2>Your coffee, in conversation.</h2><p>Compare your last shots, work out what to change, or tell me what you just brewed.</p>{['Show my recent shots.','What should I brew next?','Help me log a shot.'].map(q=><button key={q} onClick={()=>setInput(q)}>{q} ↗</button>)}</div>}{messages.map(m=><div key={m.id} className={'message '+m.role}><small>{m.role==='user'?'You':<><Icon name="cup"/>Coffee companion</>}</small>{m.role==='assistant'?<div className="markdown" dangerouslySetInnerHTML={{__html:DOMPurify.sanitize(marked.parse(m.text,{async:false}))}}/>:<div>{m.text}</div>}</div>)}{job&&<ThinkingCounter label="Working" statusText="Checking your logbook"/>}</div><ChatComposer value={input} onChange={setInput} onSend={send} busy={!!job||sending}/></main>}
  <div className="build-version" title={buildTime}>Build {buildTime?new Date(buildTime).toLocaleString(undefined,{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'development'}</div>
  <dialog ref={dialog} onCancel={e=>{if(saving)e.preventDefault();else{setDraft(null);setCoffeeDraft(null)}}}>
   <div className="dialog-header"><div><div className="eyebrow">{draft?'THE BREW DETAILS':'ON THE BAR'}</div><h2>{draft?(draft.id?'Edit shot':'Log shot'):(coffeeDraft?.id?'Coffee details':'Add coffee')}</h2></div><button disabled={saving} aria-label="Close details" onClick={()=>{setDraft(null);setCoffeeDraft(null)}}><Icon name="close"/></button></div>
   {error&&<p role="alert" className="error">{error}</p>}
   <form onSubmit={e=>{e.preventDefault();draft?saveShot():saveCoffee()}}>{draft?<>
    {draft.status==='logged'&&targetYield(draft)&&<p className="brew-target">Aim for <strong>{targetYield(draft)} g out</strong></p>}
    {draft.status==='logged'?<><div className="form-grid quick-fields output-fields">{field('stop_yield_g','Stop at · g','number')}{field('yield_g','Out · g','number')}{field('seconds','Time · s','number')}</div><div className="form-grid base-fields">{field('dose','Dose · g','number')}{field('grind','Grind')}</div></>:<div className="form-grid quick-fields">{field('dose','Dose · g','number')}{field('target_yield_g','Target out · g','number')}{field('seconds','Time · s','number')}{field('grind','Grind')}</div>}
    {draft.status==='logged'&&<><fieldset className="taste-picker feedback-row"><legend>Brew result</legend><div>{Object.entries(outcomes).filter(([value])=>value!=='choked').map(([value,label])=><button type="button" key={value} aria-pressed={(draft.outcome||'unrated')===value} onClick={()=>setDraft({...draft,outcome:value as Shot['outcome'],choked:false})}>{label}</button>)}</div></fieldset><fieldset className="taste-picker feedback-row"><legend>Taste</legend><div>{Object.entries(balances).map(([value,label])=><button key={value} type="button" aria-pressed={draft.taste_balance===value} onClick={()=>setDraft({...draft,taste_balance:draft.taste_balance===value?'':value as Shot['taste_balance']})}>{label}</button>)}</div></fieldset><fieldset className="taste-picker feedback-row"><legend>Enjoyment · how much you liked it</legend><div>{[1,2,3,4,5].map(value=><button type="button" key={value} aria-label={value+' out of 5'} title={['Poor','Fair','Nice','Lovely','Excellent'][value-1]} aria-pressed={draft.rating===value} onClick={()=>setDraft({...draft,rating:draft.rating===value?null:value})}>{value} ★</button>)}</div></fieldset></>}
    <div className="brew-switches feedback-row"><span className="settings-label">Settings</span>{tapField('paper','Paper',[['yes','Paper'],['no','No paper']])}{tapField('temp','Temp',[['0','0'],['I','I'],['II','II']])}{draft.status==='logged'&&<button type="button" className="choked-toggle" aria-pressed={draft.choked??draft.outcome==='choked'} onClick={()=>setDraft({...draft,choked:!(draft.choked??draft.outcome==='choked'),outcome:draft.outcome==='choked'?'unrated':draft.outcome})}>Choked</button>}</div>
    <label>Taste / note<input value={draft.taste} placeholder="Sweet, bitter, thin…" onChange={e=>setDraft({...draft,taste:e.target.value})}/></label>
    <details className="more-settings"><summary>More details</summary><div className="form-grid">
     {draft.status==='logged'&&field('target_yield_g','Target out · g','number')}{field('target_yield_max_g','Target up to · g (optional)','number')}{field('date','Shot date','date')}{selectField('status','Entry type',['logged','planned'])}{field('first_drip','First drip · s','number')}{field('pressure','Pressure · bar')}{field('basket','Basket')}{selectField('puck_screen','Puck screen',['yes','no','unknown'])}
    </div>{draft.source&&<details><summary>Original logbook entry</summary><p>{draft.source}</p></details>}</details>
    </>:coffeeDraft&&<><label>Coffee name<input required value={coffeeDraft.name||''} onChange={e=>setCoffeeDraft({...coffeeDraft,name:e.target.value})}/></label><fieldset className="marker-picker"><legend>Canister marker</legend><div><button type="button" className="marker-clear" aria-label="No canister marker" aria-pressed={!coffeeDraft.tag_color} onClick={()=>setCoffeeDraft({...coffeeDraft,tag_color:''})}>×</button>{markerColors.map(color=><button type="button" key={color} className={'marker-choice '+color} aria-label={color+' canister marker'} aria-pressed={coffeeDraft.tag_color===color} onClick={()=>setCoffeeDraft({...coffeeDraft,tag_color:color})}/>)}</div></fieldset><p>{coffeeDraft.archived?'Restore this coffee to use it for new shots again.':'Update the roast date for your current bag. Your shot history and ratings stay unchanged.'}</p><label>Roast date<input type="date" value={dateInput(coffeeDraft.roast_date||'')} onChange={e=>setCoffeeDraft({...coffeeDraft,roast_date:e.target.value})}/></label><label>Origin, process & notes<textarea rows={7} value={coffeeDraft.notes||''} onChange={e=>setCoffeeDraft({...coffeeDraft,notes:e.target.value})}/></label></>}<button className="primary save" disabled={saving}><Icon name="check"/>{saving?'Saving…':'Save '+(draft?'shot':'coffee')}</button></form>
   {draft?.id&&<button type="button" className="delete-record" disabled={saving} onClick={removeRecord}>Delete shot</button>}{coffeeDraft?.id&&<button type="button" className="delete-record" disabled={saving} onClick={()=>setCoffeeArchived(coffeeDraft as Coffee,!coffeeDraft.archived)}>{coffeeDraft.archived?'Restore coffee':'Archive coffee'}</button>}
  </dialog>
 </div>
}
